import { StyleSheet } from 'react-native';

import { COLORS, RADIUS, SHADOWS, SPACING, TYPOGRAPHY } from '@/src/constants';

export const styles = StyleSheet.create({
  flex1: { flex: 1 },
  scroll: { backgroundColor: COLORS.background, flex: 1 },
  content: { gap: SPACING.xxl, paddingBottom: 100, paddingHorizontal: 12, paddingTop: SPACING.xl },
  bellBtn: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },

  subHeader: { alignItems: 'center', flexDirection: 'row', gap: SPACING.md },
  backBtn: { alignItems: 'center', backgroundColor: COLORS.gray200, borderRadius: RADIUS.round, height: 34, justifyContent: 'center', width: 34 },
  titleBlock: { gap: 2 },
  pageTitle: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 18, lineHeight: 26 },
  pageDate: { ...TYPOGRAPHY.caption, color: COLORS.gray500 },

  calendarCard: {
    backgroundColor: '#F7F7F7', borderColor: '#E3E3E3', borderRadius: RADIUS.lg, borderWidth: 1,
    paddingBottom: SPACING.lg, paddingHorizontal: SPACING.xl, paddingTop: SPACING.xl,
  },
  calMonthRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: SPACING.lg, paddingHorizontal: SPACING.xs },
  calArrowGroup: { alignItems: 'center', flexDirection: 'row', gap: SPACING.xs },
  calMonthText: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 15, lineHeight: 22 },
  calWeekRow: { flexDirection: 'row', marginBottom: SPACING.xxs },
  calWeekDay: { color: COLORS.gray500, flex: 1, fontFamily: 'NotoSansKR_400Regular', fontSize: 11, lineHeight: 18, textAlign: 'center' },
  calWeekDaySat: { color: COLORS.primary },
  calWeekDaySun: { color: COLORS.danger },
  calGrid: { gap: 0 },
  calRow: { flexDirection: 'row' },
  calCell: { alignItems: 'center', flex: 1, paddingVertical: SPACING.xxs + 1 },
  calBubble: { alignItems: 'center', backgroundColor: 'transparent', borderRadius: 16, height: 32, justifyContent: 'center', overflow: 'hidden', width: 32 },
  calBubbleToday: { backgroundColor: COLORS.gray200 },
  calBubbleSelected: { backgroundColor: COLORS.primary },
  calDateText: { color: COLORS.black, fontFamily: 'NotoSansKR_400Regular', fontSize: 13, lineHeight: 20 },
  calDateTextToday: { color: COLORS.gray800, fontFamily: 'NotoSansKR_500Medium' },
  calDateTextSelected: { color: COLORS.background, fontFamily: 'NotoSansKR_700Bold' },
  calDateTextSat: { color: COLORS.primary },
  calDateTextSun: { color: COLORS.danger },
  dotRow: { alignItems: 'center', flexDirection: 'row', gap: 2, height: 4, justifyContent: 'center', marginTop: 2 },
  calDot: { borderRadius: RADIUS.round, height: 4, width: 4 },
  calProgressRow: { alignItems: 'flex-end', marginTop: SPACING.md },
  calProgressBadge: { backgroundColor: COLORS.primarySoft, borderColor: COLORS.primary, borderRadius: RADIUS.round, borderWidth: 1, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.xxs },
  calProgressText: { color: COLORS.primary, fontFamily: 'NotoSansKR_500Medium', fontSize: 11, lineHeight: 17 },

  routineHighlightBubble: { backgroundColor: COLORS.primary },
  routineHighlightText: { color: COLORS.background, fontFamily: 'NotoSansKR_700Bold' },

  sectionTitle: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 16, lineHeight: 24, marginBottom: -SPACING.sm },

  tagRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm },
  tagChip: { borderRadius: RADIUS.round, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.xs + 2 },
  tagChipText: { fontFamily: 'NotoSansKR_500Medium', fontSize: 13, lineHeight: 20 },

  taskList: { gap: SPACING.lg },
  taskCard: {
    alignItems: 'center', backgroundColor: '#F7F7F7', borderColor: '#E3E3E3',
    borderRadius: RADIUS.lg, borderWidth: 1, flexDirection: 'row',
    gap: SPACING.lg, paddingHorizontal: SPACING.xxl, paddingVertical: SPACING.xl,
  },
  taskIconWrap: { alignItems: 'center', borderRadius: RADIUS.round, height: 40, justifyContent: 'center', width: 40 },
  taskBody: { flex: 1, gap: 2 },
  taskTitle: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 14, lineHeight: 21 },
  taskTitleDone: { color: COLORS.gray500, textDecorationLine: 'line-through' },
  taskDesc: { ...TYPOGRAPHY.small, color: COLORS.gray500 },
  taskTagBadge: { borderRadius: RADIUS.round, paddingHorizontal: SPACING.md, paddingVertical: SPACING.xxs },
  taskTagText: { fontFamily: 'NotoSansKR_500Medium', fontSize: 11, lineHeight: 16 },
  taskTime: { color: COLORS.primary, fontFamily: 'NotoSansKR_700Bold', fontSize: 13, lineHeight: 20 },
  checkbox: { alignItems: 'center', borderColor: COLORS.gray300, borderRadius: RADIUS.sm, borderWidth: 1.5, height: 22, justifyContent: 'center', width: 22 },
  checkboxDone: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },

  emptyState: { alignItems: 'center', paddingVertical: SPACING.xxxl },
  emptyText: { ...TYPOGRAPHY.body2, color: COLORS.gray500, lineHeight: 22, textAlign: 'center' },

  fab: {
    alignItems: 'center', backgroundColor: COLORS.primary, borderRadius: RADIUS.round,
    elevation: 6, height: 56, justifyContent: 'center', position: 'absolute',
    right: SPACING.jumbo, shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35, shadowRadius: 8, width: 56,
  },

  overlay: { backgroundColor: COLORS.overlay, flex: 1, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: COLORS.background, borderTopLeftRadius: RADIUS.modal, borderTopRightRadius: RADIUS.modal,
    gap: SPACING.xl, paddingBottom: SPACING.jumbo, paddingHorizontal: SPACING.xxl, paddingTop: SPACING.lg,
    ...SHADOWS.modal,
  },
  sheetTall: { paddingBottom: SPACING.jumbo + 16 },
  handle: { alignSelf: 'center', backgroundColor: COLORS.gray300, borderRadius: RADIUS.round, height: 4, marginBottom: SPACING.sm, width: 40 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  sheetTitle: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 17, lineHeight: 26 },
  sheetSubtitle: { ...TYPOGRAPHY.caption, color: COLORS.gray500, marginTop: 2 },
  closeCircleBtn: { alignItems: 'center', backgroundColor: COLORS.gray200, borderRadius: RADIUS.round, height: 32, justifyContent: 'center', width: 32 },

  inputGroup: { gap: SPACING.sm },
  inputLabel: { color: COLORS.gray800, fontFamily: 'NotoSansKR_500Medium', fontSize: 13, lineHeight: 20 },
  // lineHeight 제거 → 단일 라인 TextInput 플레이스홀더 흔들림 방지
  input: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.md,
    color: COLORS.black,
    fontFamily: 'NotoSansKR_400Regular',
    fontSize: 14,
    paddingHorizontal: SPACING.xxl,
    paddingVertical: SPACING.lg,
  },
  inputMulti: { height: 76, lineHeight: 21, paddingTop: SPACING.lg },

  timeRoutineRow: { alignItems: 'stretch', flexDirection: 'row', gap: SPACING.xl },
  tagAddBtn: { alignItems: 'center', borderColor: COLORS.gray300, borderRadius: RADIUS.round, borderWidth: 1.5, height: 34, justifyContent: 'center', width: 34 },
  routineField: { justifyContent: 'space-between' },
  routineDateText: { color: COLORS.black, fontFamily: 'NotoSansKR_500Medium', fontSize: 13, lineHeight: 19 },
  routineDayText: { color: COLORS.gray500, fontFamily: 'NotoSansKR_400Regular', fontSize: 10, lineHeight: 15 },

  tagSelectRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm },
  rowField: {
    alignItems: 'center', backgroundColor: COLORS.gray100, borderRadius: RADIUS.md,
    flexDirection: 'row', gap: SPACING.sm, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.lg,
  },
  rowFieldText: { color: COLORS.black, fontFamily: 'NotoSansKR_400Regular', fontSize: 13, lineHeight: 20 },
  submitBtn: { alignItems: 'center', backgroundColor: COLORS.primary, borderRadius: RADIUS.button, marginTop: SPACING.sm, paddingVertical: SPACING.xl + 2 },
  submitBtnText: { color: COLORS.background, fontFamily: 'NotoSansKR_700Bold', fontSize: 15, lineHeight: 22 },

  timePickerWrap: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: SPACING.xxl, paddingVertical: SPACING.xxl },
  timePickerCol: { alignItems: 'center', gap: SPACING.md },
  timeArrowBtn: { alignItems: 'center', justifyContent: 'center', padding: SPACING.sm },
  timeValueBox: { alignItems: 'center', backgroundColor: COLORS.primarySoft, borderRadius: RADIUS.md, justifyContent: 'center', minWidth: 72, paddingHorizontal: SPACING.xxl, paddingVertical: SPACING.lg },
  timePickerValue: { color: COLORS.primary, fontFamily: 'NotoSansKR_700Bold', fontSize: 36, lineHeight: 44 },
  timePickerUnit: { color: COLORS.gray500, fontFamily: 'NotoSansKR_400Regular', fontSize: 13, lineHeight: 20 },
  timeColon: { color: COLORS.black, fontFamily: 'NotoSansKR_700Bold', fontSize: 32, lineHeight: 40, paddingBottom: 24 },

  tagSectionLabel: { color: COLORS.black, fontFamily: 'NotoSansKR_500Medium', fontSize: 13, lineHeight: 20 },
  tagChipWithX: { alignItems: 'center', borderRadius: RADIUS.round, flexDirection: 'row', gap: SPACING.xs, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.xs + 2 },
  suggTagChip: { backgroundColor: COLORS.background, borderColor: COLORS.gray300, borderRadius: RADIUS.round, borderWidth: 1, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.xs + 2 },
  suggTagChipText: { color: COLORS.black, fontFamily: 'NotoSansKR_400Regular', fontSize: 13, lineHeight: 20 },
  labelRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  counterText: { ...TYPOGRAPHY.caption, color: COLORS.gray500 },
  colorRow: { flexDirection: 'row', gap: SPACING.xl, justifyContent: 'center' },
  colorDot: { alignItems: 'center', borderRadius: RADIUS.round, borderWidth: 1, height: 28, justifyContent: 'center', width: 28 },
  tagFooter: { flexDirection: 'row', gap: SPACING.xl, marginTop: SPACING.sm },
  deleteBtn: { alignItems: 'center', borderColor: COLORS.gray300, borderRadius: RADIUS.button, borderWidth: 1.5, flex: 1, paddingVertical: SPACING.xl },
  deleteBtnText: { color: COLORS.gray600, fontFamily: 'NotoSansKR_500Medium', fontSize: 14, lineHeight: 21 },
  saveBtn: { alignItems: 'center', backgroundColor: COLORS.primary, borderRadius: RADIUS.button, flex: 2, paddingVertical: SPACING.xl },
  saveBtnText: { color: COLORS.background, fontFamily: 'NotoSansKR_700Bold', fontSize: 14, lineHeight: 21 },

  routineCalCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.lg, borderWidth: 1, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.sm },
  pickerCalCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.lg, borderWidth: 1, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.sm },
  routineTypeRow: { flexDirection: 'row', gap: SPACING.md },
  routineTypeChip: { alignItems: 'center', borderColor: COLORS.gray300, borderRadius: RADIUS.round, borderWidth: 1.5, flex: 1, flexDirection: 'row', gap: SPACING.xs, justifyContent: 'center', paddingVertical: SPACING.sm },
  routineTypeChipActive: { borderColor: COLORS.primary },
  routineTypeText: { color: COLORS.gray600, fontFamily: 'NotoSansKR_400Regular', fontSize: 13, lineHeight: 20 },
  routineTypeTextActive: { color: COLORS.primary, fontFamily: 'NotoSansKR_500Medium' },
  routineDayRow: { flexDirection: 'row', gap: SPACING.sm },
  routineDayChip: { alignItems: 'center', backgroundColor: COLORS.gray200, borderRadius: RADIUS.round, flex: 1, justifyContent: 'center', paddingVertical: SPACING.sm },
  routineDayChipActive: { backgroundColor: COLORS.primary },
  routineDayChipText: { color: COLORS.gray600, fontFamily: 'NotoSansKR_400Regular', fontSize: 12, lineHeight: 18 },
  routineDayChipTextActive: { color: COLORS.background, fontFamily: 'NotoSansKR_500Medium' },
  routinePeriodRow: { flexDirection: 'row', gap: SPACING.xl },
  periodLabel: { color: COLORS.gray500, fontFamily: 'NotoSansKR_400Regular', fontSize: 10, lineHeight: 15 },
});
