import { MedicalExpenseRecord, WalkRecord, WeightRecord } from './types';

export const MOCK_WEIGHT_RECORDS: WeightRecord[] = [
	{
		id: 'w-1',
		date: '2026.02.10',
		time: '오후 9:00',
		weight: 4.0,
		bodyCondition: 'ideal',
		appetite: 'normal',
		isDirectInput: true,
	},
	{
		id: 'w-2',
		date: '2026.03.15',
		time: '오후 8:40',
		weight: 4.0,
		bodyCondition: 'ideal',
		appetite: 'normal',
		isDirectInput: true,
	},
	{
		id: 'w-3',
		date: '2026.04.18',
		time: '오후 8:20',
		weight: 4.1,
		bodyCondition: 'ideal',
		appetite: 'high',
		isDirectInput: true,
	},
	{
		id: 'w-4',
		date: '2026.05.22',
		time: '오후 9:10',
		weight: 4.1,
		bodyCondition: 'ideal',
		appetite: 'normal',
		isDirectInput: true,
	},
	{
		id: 'w-5',
		date: '2026.06.12',
		time: '오후 8:50',
		weight: 4.2,
		bodyCondition: 'ideal',
		appetite: 'normal',
		isDirectInput: true,
	},
	{
		id: 'w-6',
		date: '2026.06.29',
		time: '오후 8:30',
		weight: 4.2,
		bodyCondition: 'ideal',
		appetite: 'low',
		memo: '더운 날씨 탓인지 밥을 조금 남겼어요.',
		isDirectInput: true,
	},
	{
		id: 'w-7',
		date: '2026.07.06',
		time: '오후 8:30',
		weight: 4.2,
		deltaFromLastMonth: 0.1,
		bodyCondition: 'ideal',
		appetite: 'low',
		memo: '식사 후 같은 시간대에 측정했어요.',
		isDirectInput: true,
	},
	{
		id: 'w-8',
		date: '2026.07.13',
		time: '오후 8:15',
		weight: 4.3,
		bodyCondition: 'ideal',
		appetite: 'high',
		isDirectInput: true,
	},
	{
		id: 'w-9',
		date: '2026.07.20',
		time: '오후 8:35',
		weight: 4.2,
		bodyCondition: 'ideal',
		appetite: 'normal',
		isDirectInput: true,
	},
];

export const MOCK_WALK_RECORDS: WalkRecord[] = [
	{
		id: 'wk-1',
		date: '2026.07.07',
		dayLabel: '아침 산책',
		startTime: '07:30',
		endTime: '08:10',
		durationMinutes: 40,
		distanceKm: 1.6,
		intensity: 'moderate',
		weatherText: '맑음',
		temperatureText: '23°C',
		excrement: { urination: true, defecation: true, specialNote: false },
	},
	{
		id: 'wk-2',
		date: '2026.07.09',
		dayLabel: '저녁 산책',
		startTime: '19:00',
		endTime: '19:30',
		durationMinutes: 30,
		distanceKm: 1.2,
		intensity: 'relaxed',
		weatherText: '흐림',
		temperatureText: '22°C',
		excrement: { urination: true, defecation: false, specialNote: false },
	},
	{
		id: 'wk-3',
		date: '2026.07.11',
		dayLabel: '공원 산책',
		startTime: '18:20',
		endTime: '18:58',
		durationMinutes: 38,
		distanceKm: 1.7,
		intensity: 'moderate',
		weatherText: '맑음',
		temperatureText: '25°C',
		excrement: { urination: true, defecation: true, specialNote: false },
	},
	{
		id: 'wk-4',
		date: '2026.07.13',
		dayLabel: '동네 한바퀴',
		startTime: '18:00',
		endTime: '18:38',
		durationMinutes: 38,
		distanceKm: 1.6,
		intensity: 'moderate',
		weatherText: '맑음',
		temperatureText: '24°C',
		excrement: { urination: true, defecation: true, specialNote: false },
	},
	{
		id: 'wk-5',
		date: '2026.07.14',
		dayLabel: '아침 산책',
		startTime: '07:20',
		endTime: '07:50',
		durationMinutes: 30,
		distanceKm: 1.3,
		intensity: 'relaxed',
		weatherText: '맑음',
		temperatureText: '23°C',
		excrement: { urination: true, defecation: false, specialNote: false },
	},
	{
		id: 'wk-6',
		date: '2026.07.16',
		dayLabel: '저녁 산책',
		startTime: '19:10',
		endTime: '19:45',
		durationMinutes: 35,
		distanceKm: 1.5,
		intensity: 'moderate',
		weatherText: '구름조금',
		temperatureText: '24°C',
		excrement: { urination: true, defecation: true, specialNote: false },
	},
	{
		id: 'wk-7',
		date: '2026.07.18',
		dayLabel: '주말 나들이',
		startTime: '09:00',
		endTime: '10:12',
		durationMinutes: 72,
		distanceKm: 2.0,
		intensity: 'active',
		weatherText: '구름조금',
		temperatureText: '22°C',
		excrement: { urination: true, defecation: false, specialNote: false },
	},
	{
		id: 'wk-8',
		date: '2026.07.20',
		dayLabel: '오늘 산책',
		startTime: '18:20',
		endTime: '19:05',
		durationMinutes: 45,
		distanceKm: 1.8,
		intensity: 'moderate',
		weatherText: '맑음',
		temperatureText: '24°C',
		excrement: { urination: true, defecation: true, specialNote: false },
	},
];

export const MOCK_EXPENSE_RECORDS: MedicalExpenseRecord[] = [
	{
		id: 'me-1',
		date: '2026.06.18',
		hospitalName: '고양동물병원',
		totalCost: 28000,
		paymentMethod: '신한카드',
		items: [
			{ id: 'i-1', name: '정기 예방접종', cost: 28000 },
		],
	},
	{
		id: 'me-2',
		date: '2026.07.04',
		hospitalName: '??동물병원',
		totalCost: 72000,
		paymentMethod: '카카오페이',
		receiptScanned: true,
		items: [
			{ id: 'i-2', name: '진찰료', cost: 35000 },
			{ id: 'i-3', name: '유선종양 수술', cost: 42000 },
		],
	},
	{
		id: 'me-3',
		date: '2026.07.19',
		hospitalName: '24시 이레동물병원',
		totalCost: 15000,
		paymentMethod: '카카오페이',
		items: [
			{ id: 'i-4', name: '구충제 처방', cost: 15000 },
		],
	},
];