import type {
  CommunityComment,
  CommunityPost,
  MarketCategory,
  MarketStatus,
  MarketTradeType,
  ReviewCategory,
  ReviewPost,
  StoredCommunityState,
  TalkCategory,
} from './types';

export const COMMUNITY_TABS = [
  { id: 'talk', label: '소통' },
  { id: 'market', label: '장터' },
  { id: 'review', label: '리뷰' },
] as const;

export const TALK_CATEGORIES: TalkCategory[] = [
  '전체',
  '건강상담',
  '산책친구',
  '헌혈소식',
  '동네정보',
];

export const MARKET_CATEGORIES: MarketCategory[] = [
  '전체',
  '영양제',
  '사료·간식',
  '용품',
  '기타',
];

export const MARKET_TRADE_TYPES: MarketTradeType[] = ['나눔', '판매', '교환', '구해요'];

export const MARKET_STATUSES: MarketStatus[] = ['진행 중', '예약 중', '완료'];

export const REVIEW_CATEGORIES: ReviewCategory[] = ['전체', '산책 장소', '병원', '용품샵', '미용실'];

export const COMMUNITY_AD_TEXT = '광고를 통해 수익을 얻을 광고 배너입니다.';

export const COMMUNITY_GUEST_ID = 'guest';

const AUTHOR_MONGGU = {
  location: '일산서구',
  nickname: '몽구언니',
  petName: '몽구',
  profileImageUri: null,
  userId: 'community-user-monggu',
};

const AUTHOR_ARI = {
  location: '고양시',
  nickname: '아리',
  petName: '아리',
  profileImageUri: null,
  userId: 'community-user-ari',
};

const AUTHOR_NABI = {
  location: '행신동',
  nickname: '나비집사',
  petName: '나비',
  profileImageUri: null,
  userId: 'community-user-nabi',
};

const POSTS: CommunityPost[] = [
  {
    author: AUTHOR_MONGGU,
    baseBookmarkCount: 2,
    baseReactionCounts: { like: 4 },
    body: '일요일이라 병원이 닫혀서 보호자분들 조언이 필요해요. 피하수액 처음이라 준비물이나 조심할 점을 알고 싶어요.',
    category: '건강상담',
    createdAt: '2026-07-23T08:32:00.000Z',
    id: 'talk-pihasuaek',
    kind: 'talk',
    showNeighborhood: true,
    tags: ['피하수액', '강아지'],
    title: '피하수액 경험 공유 가능할까요?',
    updatedAt: '2026-07-23T08:32:00.000Z',
  },
  {
    author: AUTHOR_ARI,
    baseBookmarkCount: 1,
    baseReactionCounts: { like: 5 },
    body: '응급실 대기 작은 병원 정보라도 있으면 공유 부탁드려요. 오늘 밤까지 진료 가능한 곳을 찾고 있어요.',
    category: '동네정보',
    createdAt: '2026-07-23T07:18:00.000Z',
    id: 'talk-night-clinic',
    kind: 'talk',
    showNeighborhood: true,
    tags: ['야간진료', '고양시'],
    title: '오늘 고양시 야간 진료 가능한 곳',
    updatedAt: '2026-07-23T07:18:00.000Z',
  },
  {
    author: AUTHOR_NABI,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 3 },
    body: '겁이 많은 고양이라 이동장 적응을 천천히 하고 있어요. 병원 가기 전에 효과 있었던 방법이 궁금해요.',
    category: '건강상담',
    createdAt: '2026-07-22T18:08:00.000Z',
    id: 'talk-carrier',
    kind: 'talk',
    showNeighborhood: false,
    tags: ['고양이', '이동장'],
    title: '이동장 적응은 보통 얼마나 걸리나요?',
    updatedAt: '2026-07-22T18:08:00.000Z',
  },
  {
    author: AUTHOR_ARI,
    baseBookmarkCount: 4,
    baseReactionCounts: { like: 0 },
    body: '신장 케어 사료를 바꾸게 되어 새 제품 한 봉 나눔합니다. 유통기한 넉넉하고 직거래 가능해요.',
    category: '사료·간식',
    createdAt: '2026-07-23T06:30:00.000Z',
    expiresAt: '2026.12.08',
    id: 'market-renal-food',
    imageCount: 4,
    kind: 'market',
    location: '마두동',
    priceLabel: '나눔',
    status: '진행 중',
    tags: ['신장케어', '미개봉'],
    title: '미개봉 신장 케어 사료',
    tradeType: '나눔',
    updatedAt: '2026-07-23T06:30:00.000Z',
  },
  {
    author: AUTHOR_MONGGU,
    baseBookmarkCount: 1,
    baseReactionCounts: { like: 0 },
    body: '두 번 착용한 소형견 하네스입니다. 세탁 완료했고 작은 강아지에게 잘 맞아요.',
    category: '용품',
    createdAt: '2026-07-23T04:46:00.000Z',
    id: 'market-harness',
    imageCount: 2,
    kind: 'market',
    location: '정발산동',
    priceLabel: '3,000원',
    status: '예약 중',
    tags: ['하네스', '소형견'],
    title: '소형견 하네스 S',
    tradeType: '판매',
    updatedAt: '2026-07-23T04:46:00.000Z',
  },
  {
    author: AUTHOR_NABI,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 0 },
    body: '고양이용 L-라이신 영양제를 구해요. 개봉품은 상태 확인 후 가격 협의하고 싶어요.',
    category: '영양제',
    createdAt: '2026-07-22T10:10:00.000Z',
    id: 'market-lysine',
    imageCount: 1,
    kind: 'market',
    location: '백석동',
    priceLabel: '가격 협의',
    status: '진행 중',
    tags: ['고양이', '영양제'],
    title: '고양이 L-라이신 구해요',
    tradeType: '구해요',
    updatedAt: '2026-07-22T10:10:00.000Z',
  },
  {
    author: AUTHOR_MONGGU,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 2 },
    body: '산책 시간 맞는 보호자분들과 천천히 걷고 싶어요. 겁 많은 아이도 편하게 올 수 있는 코스예요.',
    category: '산책친구',
    createdAt: '2026-07-22T09:24:00.000Z',
    id: 'talk-walk-friend',
    kind: 'talk',
    showNeighborhood: true,
    tags: ['산책', '호수공원'],
    title: '이번 주말 호수공원 산책 같이해요',
    updatedAt: '2026-07-22T09:24:00.000Z',
  },
  {
    author: AUTHOR_ARI,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 1 },
    body: '중형견 헌혈 가능한 아이를 찾는 글을 공유받았어요. 병원 확인 후 보호자분께 바로 연결된다고 해요.',
    category: '헌혈소식',
    createdAt: '2026-07-21T15:42:00.000Z',
    id: 'talk-blood-donation',
    kind: 'talk',
    showNeighborhood: false,
    tags: ['헌혈', '중형견'],
    title: '중형견 헌혈 가능한 아이 찾고 있어요',
    updatedAt: '2026-07-21T15:42:00.000Z',
  },
  {
    author: AUTHOR_ARI,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 0 },
    body: '사용하지 않은 방수 매트를 교환하거나 나눔하려고 해요. 필요하신 분은 편하게 문의 주세요.',
    category: '기타',
    createdAt: '2026-07-21T11:08:00.000Z',
    id: 'market-waterproof-mat',
    imageCount: 0,
    kind: 'market',
    location: '대화동',
    priceLabel: '교환 가능',
    status: '진행 중',
    tags: ['방수매트', '기타'],
    title: '반려동물 방수 매트',
    tradeType: '교환',
    updatedAt: '2026-07-21T11:08:00.000Z',
  },
  {
    author: AUTHOR_NABI,
    baseBookmarkCount: 0,
    baseReactionCounts: { like: 0 },
    body: '고양이 이동장 잠금 부품만 구하고 있어요. 호환되는 여분 부품이 있으면 가격 협의하고 싶어요.',
    category: '기타',
    createdAt: '2026-07-21T09:40:00.000Z',
    id: 'market-carrier-part',
    imageCount: 0,
    kind: 'market',
    location: '행신동',
    priceLabel: '가격 협의',
    status: '진행 중',
    tags: ['이동장', '부품', '기타'],
    title: '고양이 이동장 잠금 부품 구해요',
    tradeType: '구해요',
    updatedAt: '2026-07-21T09:40:00.000Z',
  },
  {
    author: AUTHOR_MONGGU,
    baseBookmarkCount: 2,
    baseReactionCounts: { like: 0 },
    body: '남은 배변패드를 정리합니다. 상태 확인 후 거래 완료된 글이에요.',
    category: '기타',
    createdAt: '2026-07-20T13:30:00.000Z',
    id: 'market-pad-done',
    imageCount: 0,
    kind: 'market',
    location: '주엽동',
    priceLabel: '1,000원',
    status: '완료',
    tags: ['배변패드', '거래완료'],
    title: '소형 배변패드 남은 수량',
    tradeType: '판매',
    updatedAt: '2026-07-20T13:30:00.000Z',
  },
];

export const REVIEW_POSTS: ReviewPost[] = [
  {
    author: AUTHOR_ARI,
    baseReactionCounts: { helpful: 9, notHelpful: 1 },
    body: '강아지가 많은 시간대도 동선이 넓어서 편했어요. 벤치가 많아 쉬어가기 좋았습니다.',
    category: '산책 장소',
    createdAt: '2026-07-23T05:20:00.000Z',
    detailScores: {
      kindness: 5,
      price: 4,
      revisit: 5,
    },
    id: 'review-lake-park',
    placeholderPhotoCount: 2,
    rating: 4.5,
    targetName: '일산호수공원',
    title: '호수공원 산책로가 넓고 좋아요',
    visitedAt: '2026.07.21',
  },
  {
    author: AUTHOR_MONGGU,
    baseReactionCounts: { helpful: 24, notHelpful: 2 },
    body: '대기 안내가 빠르고 설명을 차분하게 해주셔서 첫 방문인데도 안심됐어요.',
    category: '병원',
    createdAt: '2026-07-22T12:10:00.000Z',
    detailScores: {
      kindness: 5,
      price: 4,
      revisit: 5,
    },
    id: 'review-clinic',
    placeholderPhotoCount: 1,
    rating: 5,
    targetName: '파우동물병원',
    title: '야간 진료 안내가 친절했어요',
    visitedAt: '2026.07.05',
  },
  {
    author: AUTHOR_NABI,
    baseReactionCounts: { helpful: 6, notHelpful: 0 },
    body: '고양이 모래 종류가 다양하고 직원분이 입자 차이를 잘 설명해주셨어요.',
    category: '용품샵',
    createdAt: '2026-07-21T16:36:00.000Z',
    detailScores: {
      kindness: 4,
      price: 4,
      revisit: 4,
    },
    id: 'review-pet-shop',
    rating: 4,
    targetName: '나비펫 용품샵',
    title: '필요한 용품을 한 번에 볼 수 있어요',
    visitedAt: '2026.07.12',
  },
  {
    author: AUTHOR_ARI,
    baseReactionCounts: { helpful: 11, notHelpful: 1 },
    body: '겁이 많은 아이인데 천천히 적응시켜주셔서 털 정리가 깔끔하게 끝났어요.',
    category: '미용실',
    createdAt: '2026-07-20T09:54:00.000Z',
    detailScores: {
      kindness: 5,
      price: 4,
      revisit: 4,
    },
    id: 'review-grooming',
    placeholderPhotoCount: 1,
    rating: 4.5,
    targetName: '몽글몽글 미용실',
    title: '아이 성향을 잘 봐주는 미용실',
    visitedAt: '2026.07.02',
  },
];

const COMMENTS: CommunityComment[] = [
  {
    author: AUTHOR_ARI,
    body: '수액 속도는 병원에서 알려준 양을 꼭 지키는 게 좋았어요. 처음이면 영상으로 손 위치를 남겨두면 도움이 돼요.',
    createdAt: '2026-07-23T08:43:00.000Z',
    id: 'comment-pihasuaek-1',
    postId: 'talk-pihasuaek',
    updatedAt: '2026-07-23T08:43:00.000Z',
  },
  {
    author: AUTHOR_NABI,
    body: '저는 수액팩을 너무 차갑지 않게 두고 시작했어요. 불안하면 내일 병원에 전화로라도 확인해보세요.',
    createdAt: '2026-07-23T08:55:00.000Z',
    id: 'comment-pihasuaek-2',
    postId: 'talk-pihasuaek',
    updatedAt: '2026-07-23T08:55:00.000Z',
  },
  {
    author: AUTHOR_MONGGU,
    body: '고양시 동물메디컬센터 야간 접수 가능하다고 들었어요. 가기 전에 전화 먼저 해보세요.',
    createdAt: '2026-07-23T07:31:00.000Z',
    id: 'comment-night-1',
    postId: 'talk-night-clinic',
    updatedAt: '2026-07-23T07:31:00.000Z',
  },
];

export function createInitialCommunityState(): StoredCommunityState {
  return {
    comments: COMMENTS,
    posts: POSTS,
    reviewPosts: REVIEW_POSTS,
    viewerStates: {},
  };
}
